spring.application.name=gameshelf-backend

spring.application.name=gameshelf-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/gameshelf
spring.datasource.username=gameshelf
spring.datasource.password=gameshelf